# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub Code"
url = "https://github.com/dongrentianyu/Stack-Obsidian-Remnote"

[social.params]
icon = "brand-github"

[[social]]
identifier = "vercel"
name = "Vercel"
url = "https://twitter.com"

[social.params]
icon = "vercel"

[[social]]
identifier = "site"
name = "GitHub Site"
url = "https://dongrentianyu.github.io/Stack-Obsidian-Remnote/"

[social.params]
icon = "external-link"
